---
pwn_pkgs:
  - socat
  - gdb
  - gdb-multiarch
  - libc6-dbg
  - libc6-dbg:i386
  - git
  - binutils
  - gcc-multilib
  - g++-multilib
  - curl
  - wget
  - make
  - cmake
  - libssl-dev
  - build-essential
  - ruby
  - ruby-dev
  - radare2
  - netcat
  - tmux
  - nasm
  - ltrace
  - strace
  - clang
  - libz3-4
  - libcapstone3
pwn_gems:
  - one_gadget
  - seccomp-tools
  - pwntools
  - bundler
arm_pkgs:
  - g++-arm-linux-gnueabihf
  - qemu-user-static
